import os

SECRET_KEY = "top-secret"
SQLALCHEMY_DATABASE_URI = os.environ.get("DATABASE_URL", "sqlite:///db.sqlite")
SQLALCHEMY_TRACK_MODIFICATIONS = False
TWILIO_ACCOUNT_SID = "XXXX"
TWILIO_AUTH_TOKEN = "XXXX"
TWILIO_SMS_VERIFY_SERVICE_ID = "XXXX"
SENDGRID_API_KEY = "XXXX"
TWILIO_EMAIL_VERIFY_SERVICE_ID = "XXXX"
